name: CI -> Deploy to My website
on:
  push:
    branches: [ main, development ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          max_retries: 1
          server: 15.165.247.44
          user: next
          password: pndcom#123
          local_dir: "./"
          remote_dir: "./studio"
          